version: '3.8'

services:
  # قاعدة البيانات للتطوير
  postgres-dev:
    image: postgres:15-alpine
    container_name: clinic_postgres_dev
    environment:
      POSTGRES_DB: clinic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clinic_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - clinic_network_dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis للتطوير
  redis-dev:
    image: redis:7-alpine
    container_name: clinic_redis_dev
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"
    networks:
      - clinic_network_dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # الباك إند للتطوير
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: clinic_backend_dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:clinic_password@postgres-dev:5432/clinic_db
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRES_IN=7d
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - clinic_network_dev
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    command: npm run start:dev

  # الموقع للتطوير
  website-dev:
    build:
      context: ./website
      dockerfile: .docker/Dockerfile.dev
    container_name: clinic_website_dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend-dev:3000
    volumes:
      - ./website:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"
    networks:
      - clinic_network_dev
    depends_on:
      - backend-dev
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  clinic_network_dev:
    driver: bridge
